# Generated by Django 4.1 on 2023-08-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='landmark_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
