# Generated by Django 4.1 on 2023-08-04 03:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_landmark_landmark_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='museum',
            name='exhibits',
        ),
        migrations.AddField(
            model_name='museum',
            name='exhibits',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='landmark_type',
            field=models.CharField(choices=[('Human-made', 'Human-made'), ('Natural', 'Natural')], default='Human-made', max_length=50),
        ),
        migrations.AlterField(
            model_name='park',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
