# Generated by Django 4.1 on 2023-08-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_review_options_remove_museum_exhibits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
