# Generated by Django 4.1 on 2023-08-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_city_options_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
