# Generated by Django 4.1 on 2023-08-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='description',
        ),
    ]
