# Generated by Django 4.1 on 2023-08-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_remove_park_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TouristAttraction',
        ),
    ]
