# Generated by Django 4.1 on 2023-08-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_delete_touristattraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Park',
        ),
    ]
