# Generated by Django 4.1 on 2023-08-07 04:22
from django.db import migrations


CITIES = [
        {
            'name': 'Tokyo',
            'country': 'Japan',
            'population': 37393129,
            'description': 'Tokyo is the capital and largest city of Japan, known for its modern technology, vibrant culture, and rich history.',
        },
        {
            'name': 'Shanghai',
            'country': 'China',
            'population': 27380371,
            'description': 'Shanghai is a major financial hub and the largest city in China, renowned for its futuristic skyline and global influence.',
        },
        {
            'name': 'São Paulo',
            'country': 'Brazil',
            'population': 22043028,
            'description': 'São Paulo is the largest city in Brazil and South America, famous for its cultural diversity, food, and vibrant nightlife.',
        },
        {
            'name': 'Mumbai',
            'country': 'India',
            'population': 20411068,
            'description': 'Mumbai, formerly known as Bombay, is the financial and entertainment capital of India, home to Bollywood and numerous landmarks.',
        },
        {
            'name': 'Beijing',
            'country': 'China',
            'population': 20462680,
            'description': 'Beijing is the capital city of China, steeped in history and known for its iconic landmarks such as the Great Wall and Forbidden City.',
        },
        {
            'name': 'Cairo',
            'country': 'Egypt',
            'population': 20094954,
            'description': 'Cairo is the capital of Egypt and one of the oldest cities in the world, famous for its ancient monuments and vibrant culture.',
        },
        {
            'name': 'Dhaka',
            'country': 'Bangladesh',
            'population': 20040999,
            'description': 'Dhaka is the capital and largest city of Bangladesh, known for its crowded streets, colorful rickshaws, and rich history.',
        },
        {
            'name': 'Osaka',
            'country': 'Japan',
            'population': 19222665,
            'description': 'Osaka is a major city in Japan, known for its modern architecture, delicious street food, and lively entertainment districts.',
        },
        {
            'name': 'Karachi',
            'country': 'Pakistan',
            'population': 18910392,
            'description': 'Karachi is the largest city in Pakistan and a bustling metropolis, known for its diverse culture, business opportunities, and beautiful beaches.',
        },
        {
            'name': 'Istanbul',
            'country': 'Turkey',
            'population': 15425957,
            'description': 'Istanbul is a transcontinental city, straddling Europe and Asia, known for its rich history, stunning architecture, and bazaars.',
        },
        {
            'name': 'Lahore',
            'country': 'Pakistan',
            'population': 12188196,
            'description': 'Lahore is a cultural hub in Pakistan, famous for its historical monuments, vibrant festivals, and mouthwatering cuisine.',
        },
        {
            'name': 'Bangkok',
            'country': 'Thailand',
            'population': 10983000,
            'description': 'Bangkok is the capital of Thailand, known for its bustling street life, ornate temples, and delicious street food.',
        },
        {
            'name': 'Moscow',
            'country': 'Russia',
            'population': 12506468,
            'description': 'Moscow is the capital and largest city of Russia, renowned for its iconic Red Square, St. Basil\'s Cathedral, and rich history.',
        },
        {
            'name': 'Hyderabad',
            'country': 'India',
            'population': 10194075,
            'description': 'Hyderabad is a major city in India, known for its historic landmarks, IT industry, and delectable biryani.',
        },
        {
            'name': 'Seoul',
            'country': 'South Korea',
            'population': 9715427,
            'description': 'Seoul is the capital and largest city of South Korea, celebrated for its cutting-edge technology, K-pop culture, and vibrant nightlife.',
        },
        {
            'name': 'Kinshasa',
            'country': 'Democratic Republic of the Congo',
            'population': 15491196,
            'description': 'Kinshasa is the capital and largest city of the Democratic Republic of the Congo, known for its lively music and dance scene.',
        },
        {
            'name': 'Jakarta',
            'country': 'Indonesia',
            'population': 10770487,
            'description': 'Jakarta is the capital of Indonesia, known for its traffic-clogged streets, diverse culture, and vibrant markets.',
        },
        {
            'name': 'Lima',
            'country': 'Peru',
            'population': 10173288,
            'description': 'Lima is the capital and largest city of Peru, famous for its historic center, culinary scene, and cultural heritage.',
        },
        {
            'name': 'London',
            'country': 'United Kingdom',
            'population': 8982000,
            'description': 'London is the capital and largest city of the United Kingdom, famous for its historical landmarks, museums, and theaters.',
        },
        {
            'name': 'Ho Chi Minh City',
            'country': 'Vietnam',
            'population': 8385239,
            'description': 'Ho Chi Minh City, formerly known as Saigon, is a vibrant city in Vietnam, known for its bustling markets and street food.',
        },
        {
            'name': 'Bangalore',
            'country': 'India',
            'population': 11329173,
            'description': 'Bangalore, also known as Bengaluru, is a major IT hub in India, celebrated for its pleasant weather and vibrant startup culture.',
        },
        {
            'name': 'Bogotá',
            'country': 'Colombia',
            'population': 7785965,
            'description': 'Bogotá is the capital and largest city of Colombia, known for its Andean backdrop, museums, and vibrant street art.',
        },
    ]


def add_city_data(apps, schema_editor):
    City = apps.get_model('cities', 'City')

    for city_data in CITIES:
        new_city, created = City.objects.get_or_create(name=city_data['name'], defaults=city_data)
        if not created:
            # If the city already exists, update its fields if necessary
            for field, value in city_data.items():
                setattr(new_city, field, value)
            new_city.save()


def remove_city_data(apps, schema_editor):
    City = apps.get_model('cities', 'City')
    for city_data in CITIES:
        try:
            city = City.objects.get(
                name=city_data['name'],
                country=city_data['country'],
                population=city_data['population'],
                description=city_data['description'],
            )
            city.delete()
        except City.DoesNotExist:
            # Handle the case when the city does not exist in the database
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('cities', '0010_delete_park'),
    ]

    operations = [
        migrations.RunPython(
            add_city_data,
            remove_city_data
        )
    ]
